### ISSUE TITLE
Doesn't work on Tux

### ISSUE THREAD

**Issue by heinst** [dlaikhter/cutememe-generator#1]
Your tux link doesnt work. Looking at the logs, theres an error in your cute.py and after more investigation it looks like it is due to the fact that BeautifulSoup isn't installed on the system and cannot be installed as we do not have sudo rights. Also, BeautifulSoup4 would be a good upgrade :)

**Comment by dlaikhter** [comment]
I'm not too sure about that.  I just have BeautifulSoup in the same directory as the python script on tux, and it's worked in the past.  Probably Apache on tux just being fucky.  I'll double check though.

**Comment by dlaikhter** [comment]
I have it up here: http://www.dans-pants.com/cutememe-generator/  cause tux sux.
